server:
  port: 8090
  servlet:
    session:
      timeout: 120

logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wucong9827
    url: jdbc:mysql://127.0.0.1:3306/mall_demo?characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    port: 6379
    host: 127.0.0.1
    database: 0

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    # 控制台日志配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*.xml

