server:
  port: 8090

logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wucong9827
    url: jdbc:mysql://127.0.0.1:3306/mall_demo?characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*.xml



